// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erbjiehcvwqhxqdvmges.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyYmppZWhjdndxaHhxZHZtZ2VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDk1OTMsImV4cCI6MjA2NTIyNTU5M30.1CnCbtzf7GytWtZuL1bPL1d9M1f5VKRgoIf-R-r1FSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);